# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 # Pods for weatherApp
 pod 'RxSwift', "6.2.0"
 pod 'RxCocoa'
 pod 'RxDataSources'

  target 'weatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weatherAppUITests' do
    # Pods for testing
  end

end
