# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weatherApp_yagom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weatherApp_yagom
  pod 'RxSwift', "6.2.0"
  pod 'RxCocoa'
  pod 'RxDataSources'

  target 'weatherApp_yagomTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weatherApp_yagomUITests' do
    # Pods for testing
  end

end
